# Generated by Django 2.2.9 on 2020-02-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=8)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
