# Generated by Django 2.2.9 on 2020-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
