# Generated by Django 2.2.9 on 2020-02-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('places', '0002_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='facilities.Facility'),
        ),
    ]
